model_type : MLP
features_size : 100
time_series: 5000
hidden_size : 100
hidden_layers : 5
output_indices : [3]
num_epochs : 100
learning_rate : 1e-5
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4.pt
labelsFile: tensor_data_labels4.pt
splitFactor : 0.2
batch_size: 16
time_points: 1800
output_file: seeingMLP4.pt