model_type : GRU
features_avg : []
hidden_size : 1024
hidden_layers : 4
mlp_layers: 4
dropout : 0.01
output_indices : [4]
num_epochs : 100
learning_rate : 1e-4
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4_V9.pt
labelsFile: tensor_data_labels13_V9.pt
labels_names: ["Wind0"]
units: ['m/s']
splitFactor : 0.2
batch_size: 16
averaging: 2
spacing: 1
limit: 1700
output_file: Wind0GRU_V10.pt