model_type : GRU
features_size : 255
time_series: -1
hidden_size : 768
hidden_layers : 5
output_indices : [1]
num_epochs : 100
learning_rate : 1e-4
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4_V9.pt
labelsFile: tensor_data_labels13_V9.pt
labels_names: ["L0"]
units: ['m']
splitFactor : 0.2
batch_size: 16
averaging: 1
spacing: 1
limit: 1700
output_file: L0GRU_V10.pt