model_type : GRU
features_avg : []
time_series: -1
hidden_size : 1024
hidden_layers : 5
dropout : 0.02
output_indices : [6]
num_epochs : 100
learning_rate : 1e-4
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4_V9.pt
labelsFile: tensor_data_labels13_V9.pt
labels_names: ["Wind2"]
units: ['m/s']
splitFactor : 0.2
batch_size: 16
averaging: 1
spacing: 1
limit: 1700
output_file: Wind2GRU_V10.pt