model_type : GRU
features_avg : [25, 75, 150, 350, 500]
time_series: -1
hidden_size : 256
dropout : 0.01
hidden_layers : 4
output_indices : [3]
num_epochs : 100
learning_rate : 1e-4
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4_V9.pt
labelsFile: tensor_data_labels13_V9.pt
labels_names: ["Strehl"]
units: ['1']
splitFactor : 0.2
batch_size: 128
averaging: 8
spacing: 1
limit: 1700
output_file: StrehlGRU_V10.pt