model_type : MLP
input_size : 50
time_series: 9000
hidden_size : 1000
hidden_layers : 3
output_indices : [0]
num_epochs : 100
learning_rate : 1e-5
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes.pt
labelsFile: tensor_seeing.pt
splitFactor : 0.2
batch_size: 16
time_points: 1800
output_file: seeingMLP.pt