model_type : GRU
features_size : 199
time_series: -1
hidden_size : 512
hidden_layers : 5
output_indices : [5]
num_epochs : 100
learning_rate : 1e-4
dataFolder: /raid1/ml4ao/torch_data/
outputFolder: /raid1/ml4ao/torch_output/
dataFile: tensor_data_olmodes4_V7.pt
labelsFile: tensor_data_labels4_V7.pt
labels_names: ["Wind1"]
units: ['m/s']
splitFactor : 0.2
batch_size: 64
time_points: 512
sampling: all
output_file: Wind0GRU_V8.pt